server:
    port: 8081
spring:
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
#        database-platform: org.hibernate.dialect.MySQLDialect
        open-in-view: false
        hibernate:
            ddl-auto: create
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/pp_store
        username: postgres
        password: Misiontic2022++

